package br.edu.ifrs.canoas.richardburton.auth;

public enum Permissions {
    RETRIEVE_ALL_USER_GROUPS,
    CREATE_USER_GROUP,
    DELETE_USER_GROUP,
    ADD_MEMBER_TO_USER_GROUP,
    REMOVE_MEMBER_FROM_USER_GROUP,
    RETRIEVE_ALL_USER_INVITATIONS,
    CREATE_USER_INVITATION,
    REFRESH_USER_INVITATION,
    CANCEL_USER_INVITATION,
}
